### ISSUE TITLE
Does it work on Huawei P10 Lite?

### ISSUE THREAD

**Issue by MrBlood01** [mashed-potatoes/PotatoNV#59] opened 2021-04-17 10:17 UTC
Hello, I read that among the various devices there is the Huawei P10, could it work on Huawei P10 Lite with Kirin 658?

**Comment by plarfman** [comment] 2021-04-19 11:17
it does, one of the Kirin 65x bootloaders will work

**Comment by MrBlood01** [comment] 2021-04-19 20:51
@plarfman I tried to do it. But it does not work. That is, the program does not detect my smartphone. I installed the android drivers and obviously the adb tools. I have enabled USB Debugging. But it doesn't work anyway.

**Comment by plarfman** [comment] 2021-04-20 07:18
it's probably becuase you haven't installed the USB COM drivers it needs, https://files.dc-unlocker.com/share.html?v=share/18B15B9D02C945A79B1967234CECB423 here's the link

**Comment by MrBlood01** [comment] 2021-04-20 18:14
I'm sorry but I'd like to ask you a question. Because I think I misunderstood me. But do I have to buy the unlock code from DC-Uncloker?

**Comment by plarfman** [comment] 2021-04-20 20:17
@MrBlood01 Nope, just a download link from DC unlocker servers, the driver itself has nothing to do with it

**Comment by MrBlood01** [comment] 2021-04-20 20:22
@plarfman So I just have to download the tool, install the drivers and open the tool.  But I don't have the unlock code

**Comment by plarfman** [comment] 2021-04-21 07:17
@MrBlood01 what error does it give? provide screenshot

**Comment by MrBlood01** [comment] 2021-04-27 21:37
@plarfman Maybe I'm wrong "PIN".  I can't figure out what the correct test point is on the motherboard of a Huawei p10 lite

**Comment by MrBlood01** [comment] 2021-05-02 14:03
@plarfman I can't figure out how to install COM drivers. I have by downloading the file from your link. But I can't install them. Here's what happens if I open the folder: \ Huawei drivers testpoint \ Driver \ X64

![image](https://user-images.githubusercontent.com/76105951/116815887-f8d6c680-ab5f-11eb-8501-f93aca6ad830.png)

**Comment by BudDeuce** [comment] 2021-05-02 14:07
![](https://3.bp.blogspot.com/-OCUGJ5ObqPo/XUg011zhE7I/AAAAAAAAYm4/tOsV98HQ61o-mPfNnKeKKbXeIPBObv-QQCK4BGAYYCw/s1600/3wKD2oM.jpg)

**Comment by BudDeuce** [comment] 2021-05-02 14:10
Run "DriverSetup.exe" as an administrator by right-clicking it and selecting "Run as administrator" and tell me the results.

**Comment by MrBlood01** [comment] 2021-05-02 14:16
So the test point is the one indicated by the red line or should I also press on the point indicated by the black zone?

Nothing has changed, I got this message. But it's the exact same message I got when installing it normally.

**Comment by BudDeuce** [comment] 2021-05-02 14:17
Try pressing down on just the yellow circle with the tweezers first.

**Comment by MrBlood01** [comment] 2021-05-02 14:17
I tried to take it at this point while plugging in the usb port.

![image](https://user-images.githubusercontent.com/76105951/116816361-ecec0400-ab61-11eb-8092-f8612f65fa31.png)

**Comment by MrBlood01** [comment] 2021-05-02 14:18
@BudDeuce So now the drivers are installed correctly? Shouldn't it show me the COM port when I connect the device via cable?

**Comment by BudDeuce** [comment] 2021-05-02 14:18
Maybe you should press down the yellow circle and the area where the black line is pointing.

**Comment by MrBlood01** [comment] 2021-05-02 14:19
So am I supposed to create some kind of bridge between the two?

**Comment by BudDeuce** [comment] 2021-05-02 14:19
Yes, connect them at the same time using the tweezers.

**Comment by MrBlood01** [comment] 2021-05-02 14:21
I try immediately. But as I told you before, now I have connected my smartphone with active USB debus but I do not see the COM port

**Comment by BudDeuce** [comment] 2021-05-02 14:21
Send me a video of the process, please.

**Comment by MrBlood01** [comment] 2021-05-02 14:22
The process while installing the drivers?

**Comment by BudDeuce** [comment] 2021-05-02 14:23
Wait for the drivers to finish installing and then connect the phone.

It's the process where you use the tweezers and connect your phone at the same time.

**Comment by MrBlood01** [comment] 2021-05-02 14:24
I believe he has finished installing the drivers

![image](https://user-images.githubusercontent.com/76105951/116816601-e27e3a00-ab62-11eb-80a3-69ddb1650734.png)

**Comment by BudDeuce** [comment] 2021-05-02 14:25
Yep, I also believe the drivers are finished installing.

**Comment by MrBlood01** [comment] 2021-05-02 14:26
Perfect, I was thinking that I can record what happens on the screen. Because I can't use the phone while doing the operations. I need a third arm hahaha

**Comment by BudDeuce** [comment] 2021-05-02 14:27
I'm glad everything is going well for you too, if anything happens, just comment on this issue.

**Comment by MrBlood01** [comment] 2021-05-02 14:28
But have you succeeded? Does it work? 

Isn't there a risk of breaking the smartphone?

**Comment by BudDeuce** [comment] 2021-05-02 14:29
I did this with my Huawei P10 VTR-L09, everything went well.

As long as you don't touch any other components of the phone, I think you will be alright.

**Comment by MrBlood01** [comment] 2021-05-02 14:30
Perfect. So for the Huawei P10 Lite that gold dot is not enough?

**Comment by BudDeuce** [comment] 2021-05-02 14:31
I think that where the black line is pointing is to help keep the tweezers still.

**Comment by BudDeuce** [comment] 2021-05-02 14:31
I just touched the gold dot last time and that was enough for the operation to work.

**Comment by MrBlood01** [comment] 2021-05-02 14:32
okay, i try. Give me a second and above all thanks for the help

**Comment by MrBlood01** [comment] 2021-05-02 14:33
But my problem is that when I plug in the cable the software doesn't detect the device

**Comment by BudDeuce** [comment] 2021-05-02 14:33
Maybe reassemble your device and fully power it off again.

**Comment by MrBlood01** [comment] 2021-05-02 14:34
Okay, I'll try. After all, I only disconnected the battery

**Comment by BudDeuce** [comment] 2021-05-02 14:36
Don't disconnect the battery or else the device won't power on.

**Comment by MrBlood01** [comment] 2021-05-02 14:38
So the battery has to be connected? 
I was following a video on youtube he disconnected it while he breezed on the test point.

https://www.youtube.com/watch?v=YkGugQ019ZY&t=605s

**Comment by MrBlood01** [comment] 2021-05-02 14:40
In fact in this guide it does not say to disconnect the battery: https://github.com/mashed-potatoes/PotatoNV/wiki/How-to-use-PotatoNV

**Comment by plarfman** [comment] 2021-05-02 14:41
@MrBlood01 you don't have to unplug battery for testpoint, i can confirm on 2 devices

**Comment by BudDeuce** [comment] 2021-05-02 14:42
Me too.

**Comment by MrBlood01** [comment] 2021-05-02 14:43
So that's why it doesn't work. Sorry I'm an idiot hahaha. I try

**Comment by MrBlood01** [comment] 2021-05-02 14:43
Thanks guys, you are great

**Comment by BudDeuce** [comment] 2021-05-02 14:43
No problem.

**Comment by plarfman** [comment] 2021-05-02 14:44
@MrBlood01 well it will work without battery too, it dosen't matter if its plugged in or not

**Comment by MrBlood01** [comment] 2021-05-02 14:49
Guys when I press the gold dot and shield on the motherboard the phone logs on and goes into this mode:

![image](https://user-images.githubusercontent.com/76105951/116817370-53732100-ab66-11eb-8e2e-5d7989621cf5.png)

The computer doesn't detect anything.

**Comment by MrBlood01** [comment] 2021-05-02 14:50
After connecting the device I should see the COM port between my devices right?

**Comment by BudDeuce** [comment] 2021-05-02 14:50
Yes

**Comment by BudDeuce** [comment] 2021-05-02 14:50
Unplug all the other cables connecting to the motherboard where the test point is except the battery cable.

**Comment by BudDeuce** [comment] 2021-05-02 14:51
See if that works.

**Comment by MrBlood01** [comment] 2021-05-02 14:51
But now I also see this device:

![image](https://user-images.githubusercontent.com/76105951/116817435-99c88000-ab66-11eb-8008-572ff42c28be.png)

**Comment by BudDeuce** [comment] 2021-05-02 14:51
What do you see in PotatoNV?

**Comment by MrBlood01** [comment] 2021-05-02 14:51
Can I start it?

**Comment by BudDeuce** [comment] 2021-05-02 14:52
Sure

**Comment by MrBlood01** [comment] 2021-05-02 14:52
Nothing for now

![image](https://user-images.githubusercontent.com/76105951/116817474-d2685980-ab66-11eb-81e4-28e2fad44888.png)

**Comment by BudDeuce** [comment] 2021-05-02 14:53
Try the latest version of PotatoNV here https://github.com/mashed-potatoes/PotatoNV/releases/download/v2.2.0/PotatoNV-next-v2.2.0-x86.exe

**Comment by MrBlood01** [comment] 2021-05-02 14:54
Sure, give me second

**Comment by MrBlood01** [comment] 2021-05-02 14:55
![image](https://user-images.githubusercontent.com/76105951/116817551-270bd480-ab67-11eb-8d1f-e16fdf65bfe0.png)

Nothing, in my opinion there is some problem with the drivers. But did you have to manually install any drivers?

**Comment by plarfman** [comment] 2021-05-02 14:56
@MrBlood01 you have somehow booted erecovery mode, are you sure you didn't hold volume up button or something?

**Comment by MrBlood01** [comment] 2021-05-02 15:00
Yes I'm sure. I pressed on the gold dot and on the motherboard. Immediately after that I connected the cable.

I can turn it off and try again if you want

**Comment by BudDeuce** [comment] 2021-05-02 15:01
Sure.

**Comment by BudDeuce** [comment] 2021-05-02 15:02
Do you have ADB installed?

**Comment by MrBlood01** [comment] 2021-05-02 15:03
Of course I installed them from here: https://adb.clockworkmod.com/

**Comment by BudDeuce** [comment] 2021-05-02 15:03
Oh, alright then. Just wanted to make sure.

**Comment by MrBlood01** [comment] 2021-05-02 15:04
Yes yes, very clear

**Comment by BudDeuce** [comment] 2021-05-02 15:07
I found another photo of the same device with a different test point.


![](https://d.radikal.ru/d26/1801/76/af7aa00bb0fc.jpg)

**Comment by BudDeuce** [comment] 2021-05-02 15:08
Sorry, wrong device.

**Comment by MrBlood01** [comment] 2021-05-02 15:08
No maybe this is not the huawei p10 lite. Because it has a dual camera

**Comment by MrBlood01** [comment] 2021-05-02 15:10
Maybe I can open the software first and then connect the device. It might work?

**Comment by BudDeuce** [comment] 2021-05-02 15:11
Try it.

**Comment by MrBlood01** [comment] 2021-05-02 15:16
![image](https://user-images.githubusercontent.com/76105951/116818153-2294eb00-ab6a-11eb-83a7-3a68bb5c6f5c.png)

Now?

**Comment by MrBlood01** [comment] 2021-05-02 15:17
Do I still have to hold the tweezers?

**Comment by BudDeuce** [comment] 2021-05-02 15:17
Yes

**Comment by BudDeuce** [comment] 2021-05-02 15:17
Just in case it disconnects again.

**Comment by MrBlood01** [comment] 2021-05-02 15:17
But now do I have to enter some code or click on start? Should I select "Disble FBLOCK"?

**Comment by MrBlood01** [comment] 2021-05-02 15:18
So for now the tweezers are not needed?

**Comment by BudDeuce** [comment] 2021-05-02 15:18
If it has already entered the mode, I don't think the tweezers are necessary.

**Comment by MrBlood01** [comment] 2021-05-02 15:19
So block click on start?

**Comment by BudDeuce** [comment] 2021-05-02 15:19
If you want to root, I think you should disable FBLOCK.

**Comment by BudDeuce** [comment] 2021-05-02 15:19
You can click on start now.

**Comment by MrBlood01** [comment] 2021-05-02 15:20
Yes I want to root the device. But it says not recommended

**Comment by BudDeuce** [comment] 2021-05-02 15:21
FBLOCK is restricting access to most of the partitions, it is recommended to leave it disabled because it is possible to corrupt a partition without even knowing.

**Comment by MrBlood01** [comment] 2021-05-02 15:21
But if I don't select it now, will I be able to root later?

**Comment by BudDeuce** [comment] 2021-05-02 15:22
Root is more likely to happen if you have more access to more partitions.

**Comment by MrBlood01** [comment] 2021-05-02 15:23
![image](https://user-images.githubusercontent.com/76105951/116818304-05ace780-ab6b-11eb-80af-86662e51dc8c.png)

So from this situation just click on start? Don't I have to enter a code like in the guide?

**Comment by BudDeuce** [comment] 2021-05-02 15:24
There was a text box in older versions where you can write your own code. But in this version, it was no text box and it is more up-to-date and stable. Make sure you select Kirin 960 as your bootloader because that is your phone's CPU.

**Comment by BudDeuce** [comment] 2021-05-02 15:25
You are good to go.

**Comment by BudDeuce** [comment] 2021-05-02 15:25
The program generates a code for you in this latest version.

**Comment by MrBlood01** [comment] 2021-05-02 15:26
No, for the huawei p10 lite it is the Kirin 658. https://www.devicespecifications.com/en/model-cpu/8469421f

**Comment by BudDeuce** [comment] 2021-05-02 15:26
Sorry, I keep thinking that your phone is the Huawei Honor 9.

**Comment by MrBlood01** [comment] 2021-05-02 15:27
No problem if it works I have a series of huawei to unlock ahahaha

**Comment by MrBlood01** [comment] 2021-05-02 15:30
![image](https://user-images.githubusercontent.com/76105951/116818528-2164bd80-ab6c-11eb-8734-4f36af49006a.png)

Now? Should I just wait? When can I disconnect the cable?

**Comment by BudDeuce** [comment] 2021-05-02 15:31
You should be finished, I think you can reassemble the phone and disconnect the cable now.

**Comment by MrBlood01** [comment] 2021-05-02 15:32
It is formatting, is this normal?

Dadi "Ripristino impostazioni di fabbrica livello basso"

**Comment by MrBlood01** [comment] 2021-05-02 15:33
I will lose my data then. Shit hahaha

**Comment by mashed-potatoes** [comment] 2021-05-02 15:33
> ![image](https://user-images.githubusercontent.com/76105951/116818528-2164bd80-ab6c-11eb-8734-4f36af49006a.png)
> 
> Now? Should I just wait? When can I disconnect the cable?

Oof, v2.2.0 seems to be buggy.

**Comment by BudDeuce** [comment] 2021-05-02 15:34
Keep the process going and don't interrupt or else something terrible might happen.

**Comment by MrBlood01** [comment] 2021-05-02 15:34
@mashed-potatoes A screen appeared saying that the phone has been unlocked. Perhaps this is a visual bug

**Comment by BudDeuce** [comment] 2021-05-02 15:35
Is that on your phone?

**Comment by MrBlood01** [comment] 2021-05-02 15:35
Yes

**Comment by BudDeuce** [comment] 2021-05-02 15:35
That's normal.

**Comment by MrBlood01** [comment] 2021-05-02 15:36
Now it is rebooting, after I will try to go into fastboot mode

**Comment by MrBlood01** [comment] 2021-05-02 15:36
But then the data will be deleted?

**Comment by MrBlood01** [comment] 2021-05-02 15:38
Yes, I lost all data hahaha. Does nothing, check the status of the bootloader, a second.

**Comment by MrBlood01** [comment] 2021-05-02 15:45
![IMG_20210502_174359](https://user-images.githubusercontent.com/76105951/116818916-085d0c00-ab6e-11eb-97d5-b8d3c796fb9b.jpg)

It worked!  Yesssssss.  You are great guys. Really unbelievable.  Thanks a lot to everyone!

**Comment by BudDeuce** [comment] 2021-05-02 15:46
No problem.

**Comment by BudDeuce** [comment] 2021-05-02 15:46
@mashed-potatoes You can close this now.

**Closed** 2021-05-02 15:54 UTC
